### PR TITLE
[WIP] Integrating TravisCI

### PR DESCRIPTION
**Pull request by hbsock**
For setting up the CI.

### CODE REVIEW

**Comment by jaimeiturriaga** [comment]
I noticed that you removed the gemfile lock from the repository. It's very important that we all have the same gemfile lock file to make sure that we're all working on the same version for gems. This way if there's an update for a gem and someone runs bundle install, it'll check for the version that's already being used rather than the most recent version.

**Comment by hbsock** [comment]
Gemfile.lock breaks the TravisCI builds. 

I just wanted to get the CI to actually work there, so it was just a quick fix in this branch to get the CI to work.
I'll just add a pre-script in the travis config file to delete the Gemfile.lock file just for the CI, and bring it back to the repo.

**Comment by jaimeiturriaga** [comment]
If that's the case thats cool. Just an fyi also when I did bundle install it added x64 versions for some of the gems, so double check the gemfile.lock before you merge.

**Comment by hbsock** [comment]
Don't worry. I've copied the .lock file from your commit onto the master branch.

**Pull request merged**
